version: '3'
services:
  expo:
    image: onegov_img     
    build: .              
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    stdin_open: true     
    tty: true              
